development:
  google_key: "Enter your keys here. Check Read me file to know how to get keys"
  google_secret: "Enter your keys here. Check Read me file to know how to get keys"

production:
  google_key: "Enter your keys here. Check Read me file to know how to get keys"
  google_secret: "Enter your keys here. Check Read me file to know how to get keys"